services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql # Persistir BBDD 
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
    - prestashop_network

  prestashop:
    container_name: prestashop
    build: . 
    # image: prestashop/prestashop:latest # Latest stable version of the PrestaShop,
    restart: unless-stopped
    depends_on:
    - mysql
    ports:
    - 8080:80
    volumes:
      - psdata:/var/www/html # Persistir Prestashop
      - psmedia:/var/www/html/img # Persistir imágenes
      - pstranslations:/var/www/html/translations # Persistir traducciones
      - pslogs:/var/log # Persistir logs

    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
    # PS_INSTALL_AUTO: 1
      PS_DOMAIN: localhost:8080
      PS_FOLDER_ADMIN: admin4577 # Ejemplo?
      PS_FOLDER_INSTALL: install4577  # Ejemplo?
    networks:
      - prestashop_network

networks:
  prestashop_network:

volumes:
  dbdata: # Persistir BBDD
  psdata: # Persistir Prestashop
  psmedia: # Para imágenes
  pstranslations: # Persistir traducciones
  pslogs: # Para logs
